// <auto-generated />
using System;
using EntityFrameworkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231209091137_AddSeed-Student-203012091611")]
    partial class AddSeedStudent203012091611
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityFrameworkCore.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5801f726-3bd3-4524-a080-31dbde3cf4ce"),
                            Address = "Binh Tan, HCM",
                            Age = 18,
                            Name = "Datsunbae"
                        },
                        new
                        {
                            Id = new Guid("f6a50b3b-7b98-4817-a8d9-3153c2efc454"),
                            Address = "Go Vap, HCM",
                            Age = 20,
                            Name = "Kodoku"
                        },
                        new
                        {
                            Id = new Guid("b59a518d-6bb2-48b1-a569-211a09f7080f"),
                            Address = "Go Vap, HCM",
                            Age = 21,
                            Name = "Van Dat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
